# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BCryptSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCryptSwiftSample
  pod "BCryptSwift"
end
